module.exports = [
  {
    campeonato_id: 10,
    nome: "Campeonato Brasileiro",
    slug: "campeonato-brasileiro",
    nome_popular: "Brasileirão",
    edicao_atual: {
      edicao_id: 3,
      temporada: "2020",
      nome: "Campeonato Brasileiro 2020",
      nome_popular: "Brasileirão 2020",
      slug: "campeonato-brasileiro-2020",
    },
    status: "agendado",
    tipo: "Pontos Corridos",
    _link: "/v1/campeonatos/10",
  },
  {
    campeonato_id: 2,
    nome: "Copa do Brasil",
    slug: "copa-do-brasil",
    nome_popular: "Copa do Brasil",
    edicao_atual: {
      edicao_id: 2,
      temporada: "2020",
      nome: "Copa do Brasil 2020",
      nome_popular: "Copa do Brasil 2020",
      slug: "copa-do-brasil-2020",
    },
    status: "suspenso",
    tipo: "Mata-Mata",
    _link: "/v1/campeonatos/2",
  },
  {
    campeonato_id: 6,
    nome: "Campeonato Carioca",
    slug: "campeonato-carioca",
    nome_popular: "Carioca",
    edicao_atual: {
      edicao_id: 1,
      temporada: "2020",
      nome: "Campeonato Carioca 2020",
      nome_popular: "Carioca 2020",
      slug: "campeonato-carioca-2020",
    },
    status: "finalizado",
    tipo: "Misto",
    _link: "/v1/campeonatos/6",
  },
  {
    campeonato_id: 13,
    nome: "Campeonato Catarinense",
    slug: "campeonato-catarinense",
    nome_popular: "Catarinense",
    edicao_atual: {
      edicao_id: 9,
      temporada: "2020",
      nome: "Campeonato Catarinense 2020",
      nome_popular: "Catarinense 2020",
      slug: "campeonato-catarinense-2020",
    },
    status: "andamento",
    tipo: "Misto",
    _link: "/v1/campeonatos/13",
  },
  {
    campeonato_id: 11,
    nome: "Campeonato Gaúcho",
    slug: "campeonato-gaucho",
    nome_popular: "Gaúcho",
    edicao_atual: {
      edicao_id: 7,
      temporada: "2020",
      nome: "Campeonato Gaúcho 2020",
      nome_popular: "Gaúcho 2020",
      slug: "campeonato-gaucho-2020",
    },
    status: "andamento",
    tipo: "Misto",
    _link: "/v1/campeonatos/11",
  },
  {
    campeonato_id: 12,
    nome: "Campeonato Mineiro",
    slug: "campeonato-mineiro",
    nome_popular: "Mineiro",
    edicao_atual: {
      edicao_id: 8,
      temporada: "2020",
      nome: "Campeonato Mineiro 2020",
      nome_popular: "Mineiro 2020",
      slug: "campeonato-mineiro-2020",
    },
    status: "andamento",
    tipo: "Misto",
    _link: "/v1/campeonatos/12",
  },
  {
    campeonato_id: 9,
    nome: "Campeonato Paulista",
    slug: "campeonato-paulista",
    nome_popular: "Paulista",
    edicao_atual: {
      edicao_id: 5,
      temporada: "2020",
      nome: "Campeonato Paulista 2020",
      nome_popular: "Paulista 2020",
      slug: "campeonato-paulista-2020",
    },
    status: "andamento",
    tipo: "Misto",
    _link: "/v1/campeonatos/9",
  },
  {
    campeonato_id: 7,
    nome: "Copa Libertadores da América",
    slug: "copa-libertadores-da-america",
    nome_popular: "Libertadores",
    edicao_atual: {
      edicao_id: 6,
      temporada: "2020",
      nome: "Copa Libertadores da América 2020",
      nome_popular: "Libertadores 2020",
      slug: "copa-libertadores-da-america-2020",
    },
    status: "suspenso",
    tipo: "Misto",
    _link: "/v1/campeonatos/7",
  },
  {
    campeonato_id: 8,
    nome: "Copa Sulamericana",
    slug: "copa-sulamericana",
    nome_popular: "Sulamericana",
    edicao_atual: {
      edicao_id: 4,
      temporada: "2020",
      nome: "Copa Sulamericana 2020",
      nome_popular: "Sulamericana 2020",
      slug: "copa-sulamericana-2020",
    },
    status: "suspenso",
    tipo: "Mata-Mata",
    _link: "/v1/campeonatos/8",
  },
];
